# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:categories/:year/:month/:day/:title:output_ext
#relative_permalinks: true

plugins:
  - kramdown
  - jekyll-paginate

# Setup
title:            ArXiv Text Gen Searches
tagline:          'Text generation papers'
description:      'API searches for text generation papers by subtopic'
url:              https://arnicas.github.io/text-gen-arxiv-papers/
baseurl:          https://arnicas.github.io/text-gen-arxiv-papers



author:
  name:           'Lynn Cherny'
  url:            https://twitter.com/arnicas


github:
  repo:           https://github.com/arnicas/text-gen-arxiv-papers/
